version: '3.4'

services:

  sensei:
    image: sensei
    volumes:
      - type: bind
        source: /home/ubuntu/sensei
        target: /app
    ports: 
      - 8000:8000
      - 8002:8002
    
    build:
      context: .
      dockerfile: ./sensei/Dockerfile
    networks:
      backend:
        ipv4_address: 172.16.238.201
    

  leader:
    image: leader
    volumes:
      - type: bind
        source: /home/ubuntu/leader
        target: /app
    ports: 
      - 8001:8001
    build:
      context: .
      dockerfile: ./leader/Dockerfile
    networks:
      backend:
        ipv4_address: 172.16.238.200
    depends_on:
      - sensei
    
  
  follower0:
    image: follower
    volumes:
      - type: bind
        source: /home/ubuntu/follower0
        target: /app
    ports: 
      - 8880:8888
    build:
      context: .
      dockerfile: ./follower/Dockerfile   
    networks:
      - backend
    depends_on:
      - leader
  
  follower1:
    image: follower
    volumes:
      - type: bind
        source: /home/ubuntu/follower1
        target: /app
    ports: 
      - 8881:8888
    build:
      context: .
      dockerfile: ./follower/Dockerfile   
    networks:
      - backend
    depends_on:
      - leader
   
  follower2:
    image: follower
    volumes:
      - type: bind
        source: /home/ubuntu/follower2
        target: /app
    ports: 
      - 8882:8888
    build:
      context: .
      dockerfile: ./follower/Dockerfile   
    networks:
      - backend
    depends_on:
      - leader 
  follower3:
    image: follower
    volumes:
      - type: bind
        source: /home/ubuntu/follower3
        target: /app
    ports: 
      - 8883:8888
    build:
      context: .
      dockerfile: ./follower/Dockerfile   
    networks:
      - backend
    depends_on:
      - leader 

  follower4:
    image: follower
    volumes:
      - type: bind
        source: /home/ubuntu/follower4
        target: /app
    ports: 
      - 8884:8888
    build:
      context: .
      dockerfile: ./follower/Dockerfile   
    networks:
      - backend
    depends_on:
      - leader 

  follower5:
    image: follower
    volumes:
      - type: bind
        source: /home/ubuntu/follower5
        target: /app
    ports: 
      - 8885:8888
    build:
      context: .
      dockerfile: ./follower/Dockerfile   
    networks:
      - backend
    depends_on:
      - leader  

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24